// Bumps the patch version in package.json and regenerates lib/version.ts
// with the new version and the current deploy timestamp. Run before build
// so the footer stamp is baked into the bundle.
import { readFileSync, writeFileSync } from "node:fs";

const pkgPath = new URL("../package.json", import.meta.url);
const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
const [major, minor, patch] = String(pkg.version)
  .split(".")
  .map((part) => Number.parseInt(part, 10));
const version = `${major}.${minor}.${patch + 1}`;
pkg.version = version;
writeFileSync(pkgPath, `${JSON.stringify(pkg, null, "\t")}\n`);

const deployedAt = new Date().toISOString();
const versionModule = `// Auto-generated by scripts/bump-version.ts — do not edit by hand.
export const APP_VERSION = "${version}";
export const DEPLOYED_AT = "${deployedAt}";
`;
writeFileSync(new URL("../lib/version.ts", import.meta.url), versionModule);

console.log(`Version bumped to ${version}, deploy stamp: ${deployedAt}`);
